version: '2'
services:
  elasticsearch:
    # image: elasticsearch:2.4
    container_name: magento-elastic
    build: ./.docker/elasticsearch6
    environment:
      - discovery.type=single-node
      - node.name=es01m2
      - cluster.name=es-docker-cluster
      - node.store.allow_mmap=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.disable.jmx=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - M2_72-network
